# Generated by Django 4.2.1 on 2023-05-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicinedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'medicinedetails',
            },
        ),
    ]
